"$schema" = "https://railway.com/railway.schema.json"

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/nodejs/bin/node /juice-shop/build/app.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3